app:
    resource: "@AppBundle/Controller"
    type:     annotation
 
T43_yml:
    resource: "@AppBundle/Resources/config/T43_routing.yml"
    prefix:   /T43
    
T44_yml:
    resource: "@AppBundle/Resources/config/T44_routing.yml"
    prefix:   /T44   
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
    
todo:
    resource: AppBundle/Controller/TodoController
    type: rest
    prefix:   /todo  
    
      