T3_format:
  path: /alumnos/{year}.{_format}
  defaults: { _controller: AppBundle:T43:format }
  methods: [GET]
  requirements:
    year: ^\+?\d{4}
    _format: html|json    
    
numero:
  path: /magic/number
  defaults: { _controller: AppBundle:T43:magic }